module.exports = {
    EMAIL_REQUIRED: 'Email is required',
    PASSWORD_REQUIRED: 'Password is required',
    PASSWORD_REQUIREMENT: 'Password must be atleast 8 characters long, contain one number, and one special character',
    INVALID_LOGIN: 'Login request invalid',
    INCOMPLETE_REGISTER: 'Missing fields from register ensure all fields are completed',
    TITLE_REQUIRED: 'List title is required',
    INVALID_FILM: 'This film cannot be added at this time',
    LOGIN_REQUIRED: 'Must login as a user',
    INVALID_TOKEN: 'Token has not been accepted try logging in again',
    LIST_NOT_FOUND: 'A list was not found with that id',
    USER_NOT_FOUND: 'A user was not found matching those credentials',
    FILM_REQUIRED: 'A film is required in order to add review/rating',
    REVIEW_NOT_FOUND: 'A review with that id does not exist',
    REQUEST_DENIED: 'This request has been denied, you do not have the correct credentials',
    FILM_REVIEWS_NOT_FOUND: 'No reviews were found for that film',
    FILM_EXISTS_IN_LIST: 'This film is already in your list',
    SOMETHING_WENT_WRONG: 'Could not complete action, something went wrong',
    FILM_NOT_FOUND: 'Film was not found'
}